name: Deploy Asynqmon to Production

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest

    steps:
      - name: SSH proxy commmand
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.API_HOST}}
          username: root
          password: ${{ secrets.API_PASSWORD}}
          script: |
            cd /root/core/infra
            git fetch
            git checkout master
            git reset --hard origin/master
            git pull

            docker compose -f docker-compose.api.yml pull asynqmon
            docker compose -f docker-compose.api.yml up -d --no-deps --force-recreate asynqmon
